# Generated by Django 3.1.6 on 2021-02-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200, verbose_name='Логин')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль')),
                ('salt', models.TextField(verbose_name='Соль')),
                ('pub_key', models.TextField(verbose_name='Публичный ключ')),
                ('priv_key', models.TextField(verbose_name='Приватный ключ')),
                ('type_user', models.CharField(default='user', max_length=200, verbose_name='Тип пользователя')),
            ],
        ),
    ]
