# Generated by Django 3.1.3 on 2020-12-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_message', models.IntegerField(verbose_name='От кого сообщение')),
                ('to_message', models.IntegerField(verbose_name='Кому сообщение')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('message_for_me', models.TextField(verbose_name='Сообщение')),
            ],
        ),
    ]
