# Generated by Django 3.1.6 on 2021-02-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type_message',
            field=models.TextField(default='text', verbose_name='Тип сообщения'),
        ),
    ]
