# Generated by Django 3.1.6 on 2021-03-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, verbose_name='Пользователь')),
                ('name', models.CharField(max_length=200, verbose_name='Имя устройства')),
                ('type_device', models.CharField(max_length=200, verbose_name='Тип устройства')),
            ],
        ),
        migrations.CreateModel(
            name='Rosette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, verbose_name='Пользователь')),
                ('value', models.BooleanField(verbose_name='Состояние розетки')),
                ('device_id', models.IntegerField(verbose_name='ID устройства')),
            ],
        ),
        migrations.CreateModel(
            name='TempHumSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, verbose_name='Пользователь')),
                ('value_temp', models.IntegerField(verbose_name='Температура')),
                ('value_hum', models.IntegerField(verbose_name='Влажность')),
                ('device_id', models.IntegerField(verbose_name='ID устройства')),
            ],
        ),
    ]
